# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\AdicionarLivroArquivo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1120, 588)
        Dialog.setMinimumSize(QtCore.QSize(1120, 588))
        Dialog.setMaximumSize(QtCore.QSize(1120, 588))
        self.pushButton_escolher_arquivo = QtWidgets.QPushButton(Dialog)
        self.pushButton_escolher_arquivo.setGeometry(QtCore.QRect(23, 250, 121, 31))
        self.pushButton_escolher_arquivo.setObjectName("pushButton_escolher_arquivo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1131, 591))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("UI\\../design/adicionar_livro_arquivo.png"))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 292, 1061, 280))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.pushButton_escolher_instrucao = QtWidgets.QPushButton(Dialog)
        self.pushButton_escolher_instrucao.setGeometry(QtCore.QRect(150, 250, 121, 31))
        self.pushButton_escolher_instrucao.setObjectName("pushButton_escolher_instrucao")
        self.pushButton_importar = QtWidgets.QPushButton(Dialog)
        self.pushButton_importar.setGeometry(QtCore.QRect(280, 250, 121, 31))
        self.pushButton_importar.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.pushButton_importar.setObjectName("pushButton_importar")
        self.label.raise_()
        self.tableWidget.raise_()
        self.pushButton_escolher_arquivo.raise_()
        self.pushButton_escolher_instrucao.raise_()
        self.pushButton_importar.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Importar livros"))
        self.pushButton_escolher_arquivo.setText(_translate("Dialog", "Escolher arquivo"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Título"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Autor"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Ano lançamento"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Número de páginas"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Gênero"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Data de finalização"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Nota"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Editora"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Resenha"))
        self.pushButton_escolher_instrucao.setText(_translate("Dialog", "Instruções"))
        self.pushButton_importar.setText(_translate("Dialog", "Importar livros"))
