# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\AdicionarGenero.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(453, 170)
        self.pushButton_adicionargenero = QtWidgets.QPushButton(Dialog)
        self.pushButton_adicionargenero.setGeometry(QtCore.QRect(290, 110, 111, 41))
        self.pushButton_adicionargenero.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.pushButton_adicionargenero.setObjectName("pushButton_adicionargenero")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 461, 171))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("UI\\../design/adicionar_genero.png"))
        self.label.setObjectName("label")
        self.lineEdit_genero = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_genero.setGeometry(QtCore.QRect(140, 63, 241, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_genero.setFont(font)
        self.lineEdit_genero.setFrame(False)
        self.lineEdit_genero.setObjectName("lineEdit_genero")
        self.label.raise_()
        self.pushButton_adicionargenero.raise_()
        self.lineEdit_genero.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Inserir gênero"))
        self.pushButton_adicionargenero.setText(_translate("Dialog", "Adicionar gênero"))
